version: '3'

services:
  php:
    container_name: "dootask-php-${APP_ID}"
    image: "kuaifan/php:swoole-8.0.rc9"
    shm_size: "2gb"
    ulimits:
      core:
        soft: 0
        hard: 0
    volumes:
      - ./docker/crontab/crontab.conf:/etc/supervisor/conf.d/crontab.conf
      - ./docker/php/php.conf:/etc/supervisor/conf.d/php.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/log/supervisor:/var/log/supervisor
      - ./:/var/www
    environment:
      LANG: "C.UTF-8"
      MODE: "production"
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_DB_NAME: "${DB_DATABASE}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.2"
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: "dootask-nginx-${APP_ID}"
    image: "nginx:alpine"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/var/www/public
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.3"
    links:
      - php
#plugin-nginx-links#
      - fileview
    restart: unless-stopped

  redis:
    container_name: "dootask-redis-${APP_ID}"
    image: "redis:alpine"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.4"
    restart: unless-stopped

  mariadb:
    container_name: "dootask-mariadb-${APP_ID}"
    image: "mariadb:10.7.3"
    ports:
      - "${DB_OPEN_PORT:-}:3306"
    volumes:
      - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_PREFIX: "${DB_PREFIX}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.5"
    restart: unless-stopped

  fileview:
    container_name: "dootask-fileview-${APP_ID}"
    image: "kuaifan/fileview:4.1.0-SNAPSHOT-RC20"
    platform: linux/amd64
    environment:
      KK_CONTEXT_PATH: "/fileview"
      KK_OFFICE_PREVIEW_SWITCH_DISABLED: true
      KK_FILE_UPLOAD_ENABLED: true
      KK_MEDIA: "mp3,wav,mp4,mov,avi,wmv"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.7"
    restart: unless-stopped

#plugin#

networks:
  extnetwork:
    name: "dootask-networks-${APP_ID}"
    ipam:
      config:
        - subnet: "${APP_IPPR}.0/24"
          gateway: "${APP_IPPR}.1"
